"""Generate cf-02-answers.apex - writes the confirmed call outcomes into the org.

05/09/2026. Answers supplied by Hemayet for all six households:
  every one PROMPTED with the candidate list, every one SEPARATE HOUSEHOLDS,
  and every one confirming the suburb already held on the record.

Two sets of updates:
  A. the six CF-02 tasks - replace the two [UNANSWERED] lines with the answers
  B. the twelve CF-20 HOLD tasks for these six pairs - record the answer, close them

ASCII only throughout: the CLI path mangles non-ASCII into mojibake (see the
'a-EUR"' damage repaired earlier today).
"""
import json, pathlib, re, subprocess, sys

HERE = pathlib.Path(__file__).parent
OUT = HERE / "cf-02-answers.apex"

# household -> (confirmed suburb, postcode, CF-02 task id, [CF-20 task ids])
DATA = {
    "Murphy":     ("Campbelltown", "2560", "00TgK00000BTQVWUA5",
                   ["00TgK00000BTRUvUAP", "00TgK00000BTRUwUAP"]),
    "Fitzgerald": ("Chatswood",    "2067", "00TgK00000BTQVVUA5",
                   ["00TgK00000BTRUtUAP", "00TgK00000BTRUuUAP"]),
    "Tran":       ("Chatswood",    "2067", "00TgK00000BTQVUUA5",
                   ["00TgK00000BTRUnUAP", "00TgK00000BTRUoUAP"]),
    "Anderson":   ("Campbelltown", "2560", "00TgK00000BTQVRUA5",
                   ["00TgK00000BTRUxUAP", "00TgK00000BTRUyUAP"]),
    "Clark":      ("Campbelltown", "2560", "00TgK00000BTQVSUA5",
                   ["00TgK00000BTRUzUAP", "00TgK00000BTRV0UAP"]),
    "Patel":      ("Penrith",      "2750", "00TgK00000BTQVTUA5",
                   ["00TgK00000BTRV1UAP", "00TgK00000BTRV2UAP"]),
}

# UTF-8 em dash decoded as CP1252 and stored that way; still present on some
# CF-20 tasks. Normalised to a plain hyphen rather than a real dash, because the
# CLI path that produced it would just produce it again.
MOJIBAKE = "â€”"

PROMPT_LINE = (
    "Prompted, not open: the customer did not name the suburb unaided, so the three "
    "candidates (Campbelltown 2560 / Chatswood 2067 / Penrith 2750) were read out and "
    "the customer chose {sub} {pc}. That is the value already held on the record. "
    "Recorded as prompted rather than open because a prompted confirmation of the "
    "incumbent value is the weakest form this evidence takes, and the difference should "
    "be visible to whoever reads this next.")

CF20_LINE = ("CF-20: customer says the two {name} records are NOT the same household - "
             "two separate customers on the same street. Do not merge this pair.")

CF02_BLOCK = (
    "\r\n\r\n--- Answers recorded 05/09/2026 ---\r\n"
    "Supersedes the Repair note above, which was written earlier today when both "
    "either/or lines were still open. The two lines were then briefly filled with BOTH "
    "alternatives from a worked example pasted in full, so each asserted its own "
    "opposite; they have been rewritten from the confirmed answer rather than patched.\r\n"
    "Suburb confirmed: {sub} {pc} - unchanged. The address on the record was correct.\r\n"
    "Method: prompted with the candidate list.\r\n"
    "CF-20 outcome: separate households, do not merge. Written to both CF-20 tasks "
    "for this pair.")

CF20_BLOCK = (
    "\r\n\r\n--- Answered 05/09/2026 ---\r\n"
    "The two {name} records are NOT the same household: two separate customers at the "
    "same street address. DO NOT MERGE this pair.\r\n"
    "Obtained during the CF-02 service-address call, prompted with the candidate suburb "
    "list rather than answered open.\r\n"
    "Consequence for CF-01: this pair contributes no reduction to the customer count.")

def apex_escape(s):
    return (s.replace("\\", "\\\\").replace("'", "\\'")
             .replace("\r", "\\r").replace("\n", "\\n"))

def query(soql):
    # NB: no shell=True. On Windows that re-parses the arg list and breaks the
    # quoting inside the SOQL, which silently returned the wrong descriptions.
    exe = "sf.cmd" if sys.platform == "win32" else "sf"
    r = subprocess.run([exe, "data", "query", "-o", "sunrise", "-q", soql, "-r", "json"],
                       capture_output=True, text=True)
    start = r.stdout.find("{")
    if start < 0:
        sys.exit("query failed: %s" % (r.stderr or r.stdout)[:400])
    return json.loads(r.stdout[start:])["result"]["records"]

ids = [d[2] for d in DATA.values()] + [t for d in DATA.values() for t in d[3]]
recs = {r["Id"]: r for r in query(
    "SELECT Id, What.Name, Description FROM Task WHERE Id IN ('%s')" % "','".join(ids))}

lines = ["// GENERATED by build-cf-02-answers.py on 05/09/2026 - do not hand-edit",
         "// Six CF-02 tasks answered; twelve CF-20 HOLD tasks answered and closed.",
         "List<Task> ups = new List<Task>();", ""]
problems = []

for house, (sub, pc, cf02_id, cf20_ids) in DATA.items():
    # --- A. the CF-02 task -------------------------------------------------
    # Rewrite the two answer lines WHOLESALE rather than patching them. As at
    # 05/09 04:06-04:10 both alternatives from the worked example had been pasted
    # into each line, so they assert the answer and its opposite in one sentence
    # (and Fitzgerald's names the Murphy records). Patching that would preserve
    # the contradiction; replacing the whole line is the only clean fix.
    d = recs[cf02_id]["Description"]
    out, hit_prompt, hit_cf20 = [], 0, 0
    for raw in d.split("\n"):
        cr = "\r" if raw.endswith("\r") else ""
        s = raw.rstrip("\r")
        if s.lstrip().startswith("Asked open"):
            # keep only the first; any further copies are the duplicate paste
            if hit_prompt == 0:
                out.append(PROMPT_LINE.format(sub=sub, pc=pc) + cr)
            hit_prompt += 1
        elif s.lstrip().startswith("CF-20:"):
            # the ARE/are-NOT alternatives arrived either concatenated on one line
            # or split across two, depending on the task. Keep one canonical line
            # and drop the rest.
            if hit_cf20 == 0:
                out.append(CF20_LINE.format(name=house) + cr)
            hit_cf20 += 1
        else:
            out.append(raw)
    d2 = "\n".join(out)
    if hit_prompt < 1 or hit_cf20 < 1:
        problems.append("%s CF-02: expected at least 1 prompt line and 1 CF-20 line, got %d and %d"
                        % (house, hit_prompt, hit_cf20))
    for phrase in ("ARE the same household", "unprompted"):
        if phrase in d2.split("--- Answers recorded")[0]:
            problems.append("%s CF-02: contradictory text survives - %r" % (house, phrase))
    if "[UNANSWERED]" in d2.split("--- Repair")[0]:
        problems.append("%s CF-02: an [UNANSWERED] tag survives outside the repair note" % house)
    d2 += CF02_BLOCK.format(sub=sub, pc=pc)
    lines += ["// CF-02 %s" % house,
              "ups.add(new Task(Id='%s', Description='%s'));" % (cf02_id, apex_escape(d2)), ""]

    # --- B. the two CF-20 tasks -------------------------------------------
    for tid in cf20_ids:
        nm = recs[tid]["What"]["Name"].replace(" Residence", "")
        # The CF-02 outcome template was pasted into some CF-20 tasks as well, with
        # its placeholders unfilled and mojibake intact (Murphy's is why that task
        # already read Completed). Strip those stray lines; they belong on the CF-02
        # task, and an unfilled placeholder here is the same defect in a new place.
        STRAY = ("<SUBURB>", "<POSTCODE>", "did / did not", "are / are not",
                 "Confirmed service address as",
                 "Account updated, Service_Address_Unconfirmed__c cleared")
        kept, dropped = [], 0
        for raw in (recs[tid]["Description"] or "").replace(MOJIBAKE, "-").split("\n"):
            s = raw.rstrip("\r")
            if any(k in s for k in STRAY) or re.match(r"^\d{2}-\d+-2026 \d{2}/\d{2}/\d{4}", s.strip()):
                dropped += 1
                continue
            kept.append(raw)
        dd = "\n".join(kept).rstrip() + CF20_BLOCK.format(name=house)
        if dropped:
            lines.append("// %s: dropped %d stray CF-02 template line(s)" % (nm, dropped))
        lines += ["// CF-20 %s" % nm,
                  "ups.add(new Task(Id='%s', Status='Completed', Description='%s'));"
                  % (tid, apex_escape(dd)), ""]

lines += ["update ups;", "System.debug('ANS>> records updated: ' + ups.size());"]

if problems:
    print("REFUSING TO WRITE - pattern problems:", file=sys.stderr)
    for p in problems:
        print("  " + p, file=sys.stderr)
    sys.exit(1)

OUT.write_text("\n".join(lines), encoding="utf-8")
print("wrote", OUT.name, "-", len(DATA), "CF-02 tasks +",
      sum(len(d[3]) for d in DATA.values()), "CF-20 tasks")
