"""Append the customer's preferred contact number to both Kowalski CF-20 tasks.

05/09/2026. William Kowalski named 0410 110 866 on the same call that confirmed
the two records are one household. That is a survivorship signal, not just a
contact detail, so it goes on the record before any merge is proposed.

Separate from cf-20-record-answer.py because that script refuses to touch a task
that already carries an answer, which is correct - this is an addendum to one,
not a second answer.
"""
import json, pathlib, subprocess, sys

TASKS = ["00TgK00000BTRUkUAP", "00TgK00000BTRUjUAP"]

ADDENDUM = (
    "\r\n\r\n--- Addendum 05/09/2026 ---\r\n"
    "Preferred contact number, given by the customer on the same call: 0410 110 866. "
    "That is the mobile, held on William J. Kowalski Residence (001gK00001Luv6TQAR). The "
    "landline (02) 4406 1434 sits on William Kowalski Residence (001gK00001Luv43QAB).\r\n"
    "SURVIVORSHIP: on the customer's stated preference the natural survivor is the record "
    "holding 0410 110 866. Still Marcus's call, not the admin's - but note what the basis "
    "is. Every survivorship decision in this project so far has rested on record age, and "
    "record age is what produced CF-02's six unconfirmed addresses and what the CF-13 rule "
    "had to declare arbitrary. This one rests on the customer saying which number reaches "
    "them. That is the first time a merge in this org has had an actual reason.\r\n"
    "The discarded number must be written into the survivor's Description BEFORE the merge "
    "runs. Salesforce does not keep it, and a lost phone number here is the same failure as "
    "the lost addresses in CF-02.")

if not ADDENDUM.isascii():
    sys.exit("refusing: non-ASCII in the text to be written")

def apex_escape(s):
    return (s.replace("\\", "\\\\").replace("'", "\\'")
             .replace("\r", "\\r").replace("\n", "\\n"))

exe = "sf.cmd" if sys.platform == "win32" else "sf"
r = subprocess.run([exe, "data", "query", "-o", "sunrise", "-q",
                    "SELECT Id, What.Name, Description FROM Task WHERE Id IN ('%s','%s')"
                    % tuple(TASKS), "-r", "json"], capture_output=True, text=True)
if r.stdout.find("{") < 0:
    sys.exit("query failed: %s" % (r.stderr or r.stdout)[:300])
recs = json.loads(r.stdout[r.stdout.find("{"):])["result"]["records"]
if len(recs) != 2:
    sys.exit("expected 2 tasks, got %d" % len(recs))

lines = ["// GENERATED by cf-20-kowalski-preferred.py",
         "List<Task> ups = new List<Task>();", ""]
for rec in recs:
    d = rec["Description"] or ""
    if "--- Answered" not in d:
        sys.exit("refusing: %s carries no answer to append to" % rec["What"]["Name"])
    if "--- Addendum" in d:
        sys.exit("refusing: %s already carries an addendum" % rec["What"]["Name"])
    lines += ["// %s" % rec["What"]["Name"],
              "ups.add(new Task(Id='%s', Description='%s'));"
              % (rec["Id"], apex_escape(d + ADDENDUM)), ""]
lines += ["update ups;", "System.debug('PREF>> updated: ' + ups.size());"]

out = pathlib.Path(__file__).with_name("cf-20-kowalski-preferred.apex")
out.write_text("\n".join(lines), encoding="utf-8")
print("wrote", out.name, "- 2 tasks")
